package botcommands;

import java.awt.Color;
import net.dv8tion.jda.api.EmbedBuilder;
import net.dv8tion.jda.api.events.message.MessageReceivedEvent;
import net.dv8tion.jda.api.hooks.ListenerAdapter;

public class BotMenu extends ListenerAdapter {
	
	public String prefix = "!";
	
    @Override
    public void onMessageReceived(MessageReceivedEvent event) {
        // Ignore BOT messages to prevent loops
        if (event.getAuthor().isBot()) return;

        System.out.println("Received message: " + event.getMessage().getContentRaw());

        // Get the message content
        String message = event.getMessage().getContentRaw();

        // Example: Respond to a specific message
        if (message.equalsIgnoreCase("!hello")) {
            event.getChannel().sendMessage("Hello, " + event.getAuthor().getAsMention() + "!").queue();
        }
        
        if (message.equalsIgnoreCase(prefix + "help")) {
            EmbedBuilder embed = new EmbedBuilder();
            embed.setTitle("Help Guide", "");
            embed.addField("Use '!' to use my commands :)", "", false);
            embed.addField("------------------------------Commands-----------------------------------", "", false);
            embed.addField("rules", "The Official Server Rules", false);
            embed.addField("clear + [NUMBER]", "Clears messages", false);
            embed.addField("mute + (@USER)", "Mutes a user", false);
            embed.addField("unmute + (@USER)", "Unmutes a muted user", false);
            embed.addField("deafen + (@USER)", "Deafens a user", false);
            embed.addField("undeafen + (@USER)", "Undeafens a deafened user", false);
            embed.addField("ban + (@USER)", "Bans a user from server", false);

            embed.addField("join", "Brings me into the voice channel", false);
            embed.addField("leave", "Ejects me from the voice channel", false);
            embed.addField("------------------------------Bot MiniGames-----------------------------------", "", false);
            embed.addField("gn", "Guess the number im thinking of", false);
            embed.addField("flip", "flips a penny", false);
            embed.addField("roll", "rolls a die", false);
            embed.addField("dblroll", "rolls two dice", false);
            embed.addField("cat", "Random MEOW picture", false);
            embed.addField("--------------------------------Game Pings-----------------------------------", "", false);
            embed.addField("ow", "Pings the BOIS for OVERWATCH!", false);
            embed.addField("apec", "Pings the BOIS for ASEX!", false);
            embed.addField("~war", "Pings the BOIS for WAR THUNDER!", false);
            embed.addField("bo3", "Pings the BOIS for BLACK OPS 3!", false);
            embed.addField("terraria", "Pings the BOIS for Terraria!", false);
            embed.addField("risk", "Pings the BOIS for RISK!", false);
            embed.addField("gang", "Pings the BOIS for GANG BEASTS!", false);
            embed.addField("amongus", "Pings the BOIS for AMOOOOONGGGUSSSS!", false);
            embed.setFooter("----------------------------------------END---------------------------------------");
            embed.setFooter("Generated by " + event.getAuthor().getName(), event.getAuthor().getAvatarUrl());
            embed.setColor(Color.BLUE);
            event.getChannel().sendMessageEmbeds(embed.build()).queue();
            embed.clear();
        }
    }
}
